### ISSUE TITLE
[legislator-map] Advocacy group manager desires a map that analyzes descriptive representation for all county legistlators. (13)

### ISSUE THREAD

**Issue by Kimihiro02399** [code4policy/2024-b1-Local-Election-Database#11]
As an advocacy organization that cares about the descriptive representativeness of elected officials, I want a map of gaps in representation for all county legislators so that I can prove the worthiness of my cause in communication messages.

**Comment by Kimihiro02399** [comment]
Definition of Done: 
A user can hover over a sub-national unit (e.g. state, geographical region like the South) and see aggregate trends/indications of (under)representation

**Comment by Kimihiro02399** [comment]
Definition of Done: 
A user can hover over a sub-national unit (e.g. state, geographical region like the South) and see aggregate trends/indications of (under)representation

**Comment by sgrucza** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/155191175/8c27c039-872f-420e-a9bc-765e629560cd)
