### ISSUE TITLE
[Github-repo] Journalist or academic wants access to full dataset (8)

### ISSUE THREAD

**Issue by sgrucza** [code4policy/2024-b1-Local-Election-Database#12]
As an academic with a professional interest in local government and electoral politics, I want to have the means to replicate the modified data so that I feel confident enough to share the data or can revise for my own work.

**Comment by sgrucza** [comment]
Definition of Done: 

- [ ] We have uploaded the dataset or incorporated it (with proper citations) into GitHub
- [ ] We have created a repository for our project
- [ ] The repository has all datasets, code, and the Readme file

**Comment by sgrucza** [comment]
Tasks

- [ ] Copy/clone dataset into GitHub 
- [ ] Create a repository (done) 
- [ ] Create a ReadMe file (done)

**Comment by brandon-martinez-source** [comment]
- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Comment by sgrucza** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/155191175/a812350c-9a1a-4dff-9cb1-df51129a7974)
