### ISSUE TITLE
[gender-data] Advocacy group manager who wants to find gender related data (3)

### ISSUE THREAD

**Issue by sgrucza** [code4policy/2024-b1-Local-Election-Database#18]
I am an advocacy organization program manager (i.e. Emily's List) who wants to locate (find a link to) data on elections and selected gender representation. 

**SCORE: 3**

**Comment by sgrucza** [comment]
- [ ] I 
- [ ] N
- [ ] V 
- [ ] E 
- [ ] S 
- [ ] T

**Comment by sgrucza** [comment]
Definition of done

**Comment by brandon-martinez-source** [comment]
Definition of Done: 
- There is a link to the original data
- The spreadsheet downloads from the website

**Comment by sgrucza** [comment]
Tasks 
- [ ] Create a link to the data 
- [ ] Write 1-3 sentences describing the data and why it's useful

**Comment by sgrucza** [comment]
@kaziniaz86 to link to from index.html (homepage) to https://osf.io/mv5e6/ 
@sgrucza to write 1-3 sentences describing the data and why it's useful
@brandon-martinez-source else to edit

**Comment by sgrucza** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/155191175/2864ed5c-6993-46c3-965d-597ff90a1e09)

The link and description are placed on the homepage. Closing this one out!
