### ISSUE TITLE
[map] Team wants to demonstrate data visualization to the Ash Center (13)

### ISSUE THREAD

**Issue by sgrucza** [code4policy/2024-b1-Local-Election-Database#20]
As a team, we want to visualize a US map of how representative local elected officials are regarding gender so Professor Kessener and the Ash Center staff understand the value in continuing to visualize this dataset, and ultimately, post these pages (or a version of them) on the Ash Center website. 

**SOURCE: 13**

**Comment by sgrucza** [comment]
- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Comment by sgrucza** [comment]
Definition of Done

- [ ]  There's a map that loads on Javascript
- [ ]  The map visualizes a difference at a national level in representation using color
- [ ]  The map has a legend that we can use for all descriptive representation variables
- [ ] A user can screenshot it and share it (Have a few classmates test this)

**Comment by sgrucza** [comment]
Tasks

- [ ] Examine the dataset and example code 
- [ ] Create a map with data and heatmap
- [ ] Create a legend for the map 
- [ ] Embed into website

**Comment by brandon-martinez-source** [comment]
Adding to our tasks: 

- [ ] Create representation score for county executives per county

Based on our capabilities, we may want to look whether a user would like to see that data as it evolves over time and to let them toggle between years.

**Comment by sgrucza** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/155191175/acf318aa-767c-4a59-b8ad-3d7fc17ad75e)
