### ISSUE TITLE
[Ash-Style] Match the Ash Center’s layout/feel (3)

### ISSUE THREAD

**Issue by brandon-martinez-source** [code4policy/2024-b1-Local-Election-Database#36]
Definition of Done: 

- [ ] Our work is published on a Kennedy School website or linked as an example of good student work 
- [ ] A member of the Kennedy School outside our team points to our design as a positive example of a student project

**SCORE**: 3

**Comment by brandon-martinez-source** [comment]
As a team, we want the website to match the Ash Center’s layout/feel so that Prof. Kessner believes it looks good on the Ash Center website.

**Comment by brandon-martinez-source** [comment]
Tasks: 
- The coloring matches
- The fonts match
- The page width and padding look similar
- The headings/typeface (e.g. bolding, italics) look similar

**Comment by brandon-martinez-source** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/155215676/408503a4-afef-42ab-9b6e-1bb175610337)

**Comment by sgrucza** [comment]
New Ash Center website development as an example https://www.figma.com/file/tT1XEYdTOuK7iEJeWgKevy/AshCenter_FinalDesigns?type=design&node-id=4180%3A37357&mode=dev 



![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/155191175/05d37cc0-9004-4dfe-96cf-2541ef432e34)

**Comment by sgrucza** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/155191175/09a40b72-5ef4-46dd-8725-31b39e79844c)
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/155191175/aa1431d2-db18-4d14-80d1-425a75027643)
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/155191175/6639d7aa-639c-449c-aad3-2c322815ab34)
