### ISSUE TITLE
[Menu] Navigation Tools (3)

### ISSUE THREAD

**Issue by brandon-martinez-source** [code4policy/2024-b1-Local-Election-Database#37]
As Professor Justin de Benedictis Kessner, I want to navigate the project as easily as I would an Ash Center website so that I can get a sense of what my work would be like on the Ash website. 

SCORE: 3

**Comment by sgrucza** [comment]
- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Comment by brandon-martinez-source** [comment]
Definition of Done: 
An Ash Center staff member outside our team decides to navigate through all the pages
An Ash Center staff member outside our team can report where they can find our map, information about citations, and the original dataset

**Comment by brandon-martinez-source** [comment]
Tasks: 

- [ ] There are buttons leading to the data visualizations we have
- [ ] We have an icon logo that takes users to the home page.
- [ ] We have a footer that links to our important pages and policies.
- [ ] We have a menu.

**Comment by Kimihiro02399** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/151773686/96a55a2f-589f-4a32-98ba-2af1364e6a5d)
