### ISSUE TITLE
[Gender-data-tooltip] Advocacy manager wants to quickly see level of representation (5)

### ISSUE THREAD

**Issue by brandon-martinez-source** [code4policy/2024-b1-Local-Election-Database#39]
Definition of Done:

- [x] A user hovers over a county and see a value of representation that is something like: number of elections, number of women elected, proportionality percentage, score
- [x] A user finds and copies at least one useful stat from the website about representation

**Comment by brandon-martinez-source** [comment]
- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Comment by Kimihiro02399** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/151773686/36fb9a57-46eb-4b0f-a3c1-87e603122cdb)
