### ISSUE TITLE
Journalist wants to understand why this website was created (1)

### ISSUE THREAD

**Issue by sgrucza** [code4policy/2024-b1-Local-Election-Database#52]
As a journalist, I want to know why this website was created so that I better understand what I'm referencing and how it relates to the original dataset. 

SCORE: 1

**Comment by sgrucza** [comment]
- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Comment by sgrucza** [comment]
Definition of doner: 

- There's a clear explanation on the website about why this website was created
- The explanation is easy to find
- Professor Mehta agrees it's helpful to understand the website as a product

**Comment by sgrucza** [comment]
Tasks: 

- Add to about page information about the course and team members

**Comment by Kimihiro02399** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/151773686/74e623f8-283e-4401-919e-0b4084e11e69)
