### ISSUE TITLE
External Validity of the Data (0)

### ISSUE THREAD

**Issue by brandon-martinez-source** [code4policy/2024-b1-Local-Election-Database#56]
As a journalist interested in issues of electoral representation, I want to know if this platform is representative of all elections in the U.S. (or comprehensive/a full census of the data) so that I can cite the top-line results and indicators.

**SCORE:** 0

**Comment by brandon-martinez-source** [comment]
Definition of Done: 
-

**Comment by Kimihiro02399** [comment]
- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Comment by sgrucza** [comment]
Task 
- Include a clear mention on the website about the population used in the original dataset
