### ISSUE TITLE
[gender-data] Advocacy group manager who wants to find gender related data (0)

### ISSUE THREAD

**Issue by sgrucza** [code4policy/2024-b1-Local-Election-Database#57]
I am an advocacy organization program manager (i.e. Emily's List) who wants to locate (find a link to) data on elections and selected gender representation so that I can share the information and source and/or verify that there's real data underneath.

SCORE: 0

**Comment by sgrucza** [comment]
- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Comment by sgrucza** [comment]
Definition of Done:

- There is a link to the original data
- The spreadsheet downloads from the website

**Comment by sgrucza** [comment]
Tasks
- [ ]  Create a link to the data
- [ ]  Write 1-3 sentences describing the data and why it's useful
- [ ] Ensure button reads "download"

**Comment by sgrucza** [comment]
@sgrucza to edit

**Comment by Kimihiro02399** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/151773686/86d43337-9fd6-40d2-90ba-764896e7d840)
