### ISSUE TITLE
Rubric-Visualization (3)

### ISSUE THREAD

**Issue by brandon-martinez-source** [code4policy/2024-b1-Local-Election-Database#62]
As a team, we want our visualization to follow the rubric so that we get 100%.

**SCORE**: 3

**Comment by brandon-martinez-source** [comment]
Definition of Done: 

- [ ] A professor or TF has confirmed that our visualization and website are following the rubric.

**Comment by sgrucza** [comment]
- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Comment by sgrucza** [comment]
Task:
- Know our audience and discuss what our point is
- Add a header
- Add a subhead
- Add a clear citation

**Comment by sgrucza** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/155191175/f835d7d7-80e4-456e-b615-55a442ed0789)
