### ISSUE TITLE
Gender Web Page (3)

### ISSUE THREAD

**Issue by brandon-martinez-source** [code4policy/2024-b1-Local-Election-Database#63]
As an advocacy program manager (i.e. Emily's List), I want to navigate to the page that discusses the candidate demographics I want represented more so that I can focus only on the constituencies that matter to me.

**SCORE**: 3

**Comment by kaziniaz86** [comment]
Definitions of done:

- [ ] Such a page summarizing and discussing candidate demographics exists.

- [ ] Anyone can easily find and navigate to the page.

Tasks:

- [ ] Create the page with summary demographics data.
- [ ] Create either a link on the home or any other relevant page or create a tab/button in the navigation bar that takes users to the page.

**Comment by Kimihiro02399** [comment]
![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/151773686/20fb1d43-c900-48af-98ca-71a5a4995514)



![Image](https://github.com/code4policy/2024-b1-Local-Election-Database/assets/151773686/264ff678-259a-4ff1-929a-e19026560c1c)
