### ISSUE TITLE
Rubric-Website (5)

### ISSUE THREAD

**Issue by brandon-martinez-source** [code4policy/2024-b1-Local-Election-Database#68]
As a team, we want to develop working software that meets the users' needs defined in spring two so that we get 100% on the project.

**SCORE**: 5

**Comment by brandon-martinez-source** [comment]
Definition of Done:

- [ ] A professor or TF has confirmed that our visualization are following the rubric.

**Comment by Kimihiro02399** [comment]
- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Comment by sgrucza** [comment]
Tasks: 
- Storytime for sprint two 
- Sprint two planning 
- Team members checking regularly
- Final check to ensure all stories are met by end of sprint
