### ISSUE TITLE
Rubric-Code (3)

### ISSUE THREAD

**Issue by brandon-martinez-source** [code4policy/2024-b1-Local-Election-Database#69]
As a team, we want the code to look organized and clean so that we get 100% on the project.

Definition of Done:

- [ ] A professor or TF has confirmed that our code organization is following the rubric.

**SCORE**: 3

**Comment by Kimihiro02399** [comment]
- [ ] I
- [ ] N
- [ ] V
- [ ] E
- [ ] S
- [ ] T

**Comment by brandon-martinez-source** [comment]
As a team, we want the code to look organized and clean so that we get 100% on the project.

**Comment by sgrucza** [comment]
Tasks:

- Continue to code in a clear manner (use descriptive headers and comments throughout CSS, HTML and JS)
- Tag the product owner during pull requests
- Check the code before submitting
